### ISSUE TITLE
Frogs still spawn too often

### ISSUE THREAD

**Issue by WenXin20** [GreatOrator/TolkienTweaks-Mobs#14]
## Description
Sorry to have to bring this back up, but frogs still spawn too often, causing a lot of lag. Disabling frogs from spawning still doesn't work either.
They seem to be spawning in a strange grid-like pattern and don't move from the spot. This is happening everywhere, in this case I was in The Shire biome.
Thanks!

## Base information
* Minecraft version: 1.12.2
* Minecraft Forge version: 14.23.2810
* TolkienTweaks-Mobs version: 1.7.14.33.0

## Crash report
No crash, but here are example images:
![2019-02-06_14 57 57](https://user-images.githubusercontent.com/12000593/52510453-9b8e7d80-2bc1-11e9-8a05-d7d804c02632.png)
As you can see from the purple dots in the minimap, they are everywhere
![2019-02-06_14 57 28](https://user-images.githubusercontent.com/12000593/52510465-b3fe9800-2bc1-11e9-8c5d-eb8fb48c06dc.png)

**Comment by WenXin20** [comment]
I think I figured out what was happening. It seems like the mod [Multi mob](https://minecraft.curseforge.com/projects/multi-mob-core), which is required for Primitive Mobs, causes this to happen. 
I realized this might be the case when I found Project Vibrant Journeys' clam mobs spawning in the same way, but in the water. 
Although I'm not positive this was the cause of the problem, I haven't noticed Frogs spawning crazily anymore.

**Comment by GreatOrator** [comment]
Well, that's good, though I will admit, I was seeing them spawn abnormally in my test world, I just posted an update this morning that "should" fix it.  At the very least in my test world they were not crazy out of control and the pawning configs should work now as well.

Keep in mind the configs have natural spawning off by default so if you want them re-enabled you have to change the config.

let me know how it works with the latest update and we'll close this if everything seems ok :D

**Comment by WenXin20** [comment]
Ok, thanks, I'll check it out.

**Comment by WenXin20** [comment]
I got a[ duplicate stat id crash](https://gist.github.com/WenXin20/f7c6c10f91252adc551bb4f7a8df3079), so I can't test it yet.

**Comment by GreatOrator** [comment]
Interesting, I can't replicate the crash.  Was this on a new world?

**Comment by WenXin20** [comment]
I got this on game load. I didn't add any new mods, so I'm assuming a new stat was added that conflicts with another mod.

**Comment by GreatOrator** [comment]
Does one of the other mods you have add frogs or something similar?

**Comment by WenXin20** [comment]
Yeah, the [Mubble mod](https://minecraft.curseforge.com/projects/mubble) adds Toads from Mario.

**Comment by GreatOrator** [comment]
Ok, once the new release is available on curse try it, I renamed the frog to something different that shouldn't clash with the other mod

**Comment by WenXin20** [comment]
Frogs don't seem to be over spawning anymore. :)
