### ISSUE TITLE
The Goat becomes the horse model with Ice and Fire

### ISSUE THREAD

**Issue by WenXin20** [GreatOrator/TolkienTweaks-Mobs#15]
## Description
The gorgon head from Ice and Fire can turn mobs into an entity stone statue by holding right-click, but for some reason, when turning a goat to stone, it becomes a stone horse statue instead. Other mobs from this mod works fine.

## Base information
* Minecraft version: 1.12.2
* Forge version: 14.23.5.2810
* TolkienTweaks-Mobs version: 1.10.65.03.0
* Ice and Fire version: 1.6.1

## Image
The statues to the right are goats, but instead look like horses:
![2019-03-03_16 29 53](https://user-images.githubusercontent.com/12000593/53777465-13994c00-3ebf-11e9-8231-fef92ca78a10.png)

**Comment by GreatOrator** [comment]
Interesting, will have to take a look at my code and see what's different with the goat versus other mobs I extend

**Comment by GreatOrator** [comment]
Is this still happening?  I have not been able to replicate it

**Comment by WenXin20** [comment]
I don't know. I haven't played with these two mods together in a long time.

**Comment by GreatOrator** [comment]
Alright.  Going to close this as I have been unable to replicate it myself.

If it happens again we can reopen.
