### ISSUE TITLE
Milestone Button Reposition Config Option

### ISSUE THREAD

**Issue by WenXin20** [GreatOrator/TolkienTweaks-Mobs#16]
## Description

- An option to reposition the Milestone button in the inventory screen would be nice.
- Currently, I have another mod (Quick Store) that adds a button, but this mod overlaps it.

## Base information
* Minecraft version: 1.12.2
* Minecraft Forge version: 14.23.5.2838
* TolkienTweaks-Mobs version: 1.12.18.73.0
* [Quick Store](https://www.curseforge.com/minecraft/mc-mods/quick-store) version: 1.2

## Screenshot
![2019-07-07_20 14 03](https://user-images.githubusercontent.com/12000593/60776991-6b59f500-a0f5-11e9-8f4b-38c1779c30a1.png)

**Comment by GreatOrator** [comment]
This needs to go in https://github.com/brandon3055/Tolkien-Tweaks/issues, it is a different mod

**Comment by WenXin20** [comment]
Thanks, it is at brandon3055/Tolkien-Tweaks#1 now.
