### ISSUE TITLE
Crash w/ Pyrotech

### ISSUE THREAD

**Issue by WenXin20** [GreatOrator/TolkienTweaks-Mobs#17]
#### Issue Description

I have a crash that occurs after mining any ore from this mod, involving the mod Pyrotech.

#### Crash Log

[Link](https://paste.dimdev.org/gufohoduxu.mccrash)

#### Affected Versions

* Minecraft: v1.12.2
* Forge: v14.23.5.2838
* Dropt: v1.15.1
* [Pyrotech](https://www.curseforge.com/minecraft/mc-mods/pyrotech): v1.2.8
* Athenaeum: v1.17.3
* Tolkien Mobs: v1.12.19.41.0

For more information, see codetaylor/pyrotech#139

**Comment by GreatOrator** [comment]
Thank you, I am looking in to it right now.

**Comment by codetaylor** [comment]
@GreatOrator Hi,

Regarding your comment:

> Sorry to comment on closed issue, but codetaylor, do you possibly have any ideas on how to fix this? I am currently looking at it but the challenge is because I need to check for meta due to how I manage my different ores

I think I'd try using the given `IBlockState` instead of calling `world.getBlockState(pos)` to retrieve the `IBlockState`. So...

Instead of this:

```java
@Override
public ItemStack getItem(World world, BlockPos pos, IBlockState state) {
    int oreTypeDrop = world.getBlockState(pos).getValue(ORE_TYPE).getMeta();

    return new ItemStack(this, 1, oreTypeDrop);
}
```

Try using the given `IBlockState` parameter:

```java
@Override
public ItemStack getItem(World world, BlockPos pos, IBlockState state) {
    int oreTypeDrop = state.getValue(ORE_TYPE).getMeta();

    return new ItemStack(this, 1, oreTypeDrop);
}
```

**Comment by GreatOrator** [comment]
Thank you, funny how it is that simple to fix...I was WAY over complicating that.

**Comment by codetaylor** [comment]
You're welcome :)

**Comment by GreatOrator** [comment]
Should be fixed in https://github.com/GreatOrator/TolkienTweaks-Mobs/commit/f6efba7d71d6825107ca33aeddbad3e9b7e4cd0e had to wait till I finalized another feature I added to the mod.  let me know if you have any other issues.
