### ISSUE TITLE
Crash when hitting mithril golem

### ISSUE THREAD

**Issue by mitchngwen** [GreatOrator/TolkienTweaks-Mobs#20]
## Description
Minecraft crashes when hitting legendary mithril golem

## Base information
* Minecraft version:1.12.2
* Minecraft Forge version:2847
* TolkienTweaks-Mobs version:27.83.0

## Crash report
```
CRASH REPORT HERE
```

**Comment by GreatOrator** [comment]
do you have a crash report?

**Comment by Rogue238** [comment]
I have one.  There was a TNT explosion when it crashed.

https://paste.dimdev.org/ayeketokac.mccrash

However, I am playing on a modpack using the mod version: 28.31.0
You may have already fixed this in an updated version.  I try that out later.  Thanks for taking the time to work on this mod.  It just keeps getting better.

**Comment by ClaudiusMinimus** [comment]
My game also crashes when I hit a Mithril Golem
https://paste.ee/p/H3hHS

**Comment by GreatOrator** [comment]
Thank you, sorry I have not gotten back on this yet, the holiday season has been stupid busy for me but this is still on my radar. If all goes well I should be able to take a deep look at this right after christmas.

**Comment by GreatOrator** [comment]
Should be fixed now, latest version pushed to curse, 1.12.30.37 commit #936d558.

Let me know and Merry Christmas!
