### ISSUE TITLE
Mod Crash during Forge Loading Process

### ISSUE THREAD

**Issue by BaldisBasicsPlus** [GreatOrator/TolkienTweaks-Mobs#23]
Crash when Forge is loading mods

I have Brandoncore, the latest version
* Minecraft version: 1.12.2
* Minecraft Forge version: 14.23.5.2855
* TolkienTweaks-Mobs version: Latest

[crash-2021-06-19_15.13.35-client.txt](https://github.com/GreatOrator/TolkienTweaks-Mobs/files/6681301/crash-2021-06-19_15.13.35-client.txt)

**Comment by GreatOrator** [comment]
Basically another mod has a dwarf and has named it exactly the same as mine.  You can try to disable dwarves in the mod config to see if that works or try to find out who else is adding a dwarf and reach out to them as I have begun updating to 1.16 so am not going back to 1.12 to update.
